sudo: required
dist: trusty
language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:paparazzi-uav/ppa -y
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
  - wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
  - sudo apt-get update -q
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
install:
  - sudo apt-get install -y --force-yes paparazzi-dev paparazzi-jsbsim gcc-arm-embedded gcc-arm-linux-gnueabi libipc-run-perl rustc cargo libgazebo7-dev
script:
  - arm-none-eabi-gcc --version
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then make test_all_confs; else make test; fi; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "jAar1cuq5FiOX9mSa3VxQa8BCf78JrHLQAzUSF5HOQx3ZBhGdTHaPM/ht79cOhXTI5bYaMaq6oPNkYjNLAqBs1FoeJ9woz4unEbAQ0OSowtV7galoY+KJdcIlOECi0SVuKGzjdHrZ67ONUtTwkefKYg9ngwSyu5IxUcp8D5+oIU="

addons:
  coverity_scan:
    project:
      name: "paparazzi/paparazzi"
      description: "Build submitted via Travis CI"
    notification_email: paparazzi-builds@nongnu.org
    build_command_prepend: make ext; cov-configure --comptype gcc --compiler arm-none-eabi-gcc --template
    build_command: make test_coverity
    branch_pattern: coverity_scan

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4187f8dda7a22a92b749
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
